spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}

logging:
  file:
    path: /opt/taskify/logs