server:
  port: 8088
  servlet:
    context-path: /api
    application-display-name: taskify-api
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  swagger-ui:
    operations-sorter: method
  api-docs:
    path: /api-docs
logging:
  file:
    path: target/logs