server:
  port: 8088
spring:
  datasource:
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/taskify?currentSchema=taskifyschema