spring:
  datasource:
    username: root
    password: T0dc5IsGFhX3xLbAe9S18oM764Z2ztrn
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://hkg1.clusters.zeabur.com:31687/taskify_db